export const permissions = [
  ...[
    'tenant:list',
    'department:list',
    'department:manage',
    'project:list',
    'project:create',
    'project:update',
    'task:create',
    'task:update',
    'approval:create',
    'approval:action',
    'audit:view',
    'file:upload',
  ].map((code, index) => ({
    id: index + 23,
    name: code,
    code,
    description: code,
  })),
  { id: 1, name: '用户查询', code: 'user:list', description: '查看用户列表' },
  { id: 2, name: '用户创建', code: 'user:create', description: '新增用户' },
  { id: 3, name: '用户更新', code: 'user:update', description: '修改用户' },
  { id: 4, name: '用户删除', code: 'user:delete', description: '删除用户' },
  { id: 5, name: '角色查询', code: 'role:list', description: '查看角色列表' },
  { id: 6, name: '角色创建', code: 'role:create', description: '新增角色' },
  { id: 7, name: '角色更新', code: 'role:update', description: '修改角色' },
  { id: 8, name: '角色删除', code: 'role:delete', description: '删除角色' },
  { id: 9, name: '菜单查询', code: 'menu:list', description: '查看菜单' },
  { id: 10, name: '菜单创建', code: 'menu:create', description: '新增菜单' },
  { id: 11, name: '菜单更新', code: 'menu:update', description: '修改菜单' },
  { id: 12, name: '菜单删除', code: 'menu:delete', description: '删除菜单' },
  { id: 13, name: '内容查询', code: 'content:list', description: '查看内容' },
  { id: 14, name: '内容创建', code: 'content:create', description: '新增内容' },
  { id: 15, name: '内容更新', code: 'content:update', description: '修改内容' },
  { id: 16, name: '内容删除', code: 'content:delete', description: '删除内容' },
  {
    id: 17,
    name: '仪表盘查看',
    code: 'dashboard:view',
    description: '查看仪表盘',
  },
  {
    id: 18,
    name: '角色授权',
    code: 'role:permission',
    description: '配置角色权限',
  },
  { id: 19, name: '日志查看', code: 'log:view', description: '查看系统日志' },
  {
    id: 20,
    name: '系统设置查看',
    code: 'settings:view',
    description: '查看系统设置',
  },
  {
    id: 21,
    name: '数据分析查看',
    code: 'analytics:view',
    description: '查看经营分析与趋势数据',
  },
  {
    id: 22,
    name: '数据中心查看',
    code: 'data:view',
    description: '查看经营数据中心',
  },
];
