/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElSpace: typeof import('element-plus/es')['ElSpace'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    Header: typeof import('./../src/components/Header/index.vue')['default'];
    NButton: typeof import('naive-ui')['NButton'];
    NSpace: typeof import('naive-ui')['NSpace'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default'];
    TButton: typeof import('tdesign-vue-next')['Button'];
    TSpace: typeof import('tdesign-vue-next')['Space'];
  }
}
